Bugfix for missing dependencies
Avoids the following stack trace if neither PySide nor PyQT are available:
> NameError: name 'binding' is not defined